name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Use --legacy-peer-deps to avoid dependency conflicts
      - name: Install dependencies with legacy-peer-deps
        run: npm install --legacy-peer-deps

      - name: Run npm start
        run: npm start
